apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.proxy.name }}
  namespace: proxy
  labels:
{{- toYaml .Values.proxy.labels | nindent 4 }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
{{- toYaml .Values.proxy.labels | nindent 6 }}
  template:
    metadata:
      labels:
{{- toYaml .Values.proxy.labels | nindent 8 }}
    spec:
      containers:
      - name: {{ .Values.proxy.name }}
        image: {{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.proxy.containerPorts.nginx }}
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: {{ .Values.proxy.name }}-config
