apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.name }}-secret
  namespace: db
type: Opaque
data:
  {{- range $k, $v := .Values.db.secrets }}
  {{ $k }}: {{ $v | b64enc | quote }}
  {{- end }}
