db:
  name: wp-database
  labels:
    id: c0905643
    app: db
    env: dev
  image:
    repository: mariadb
    tag: latest
    pullPolicy: IfNotPresent
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
  containerPorts:
      mysql: 3306